package GUI;


import java.awt.Color;
import java.awt.Toolkit;
import static javafx.scene.paint.Color.color;
import sun.awt.image.ToolkitImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adel
 */
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Utama extends javax.swing.JFrame {
    ImageIcon icon;

    /**
     * Creates new form Utama
     */
    public Utama() {
        initComponents();
        icon = new ImageIcon("src/img/logo1.jpg");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pJenisLayanan = new javax.swing.JPanel();
        lJenis = new javax.swing.JLabel();
        pPelanggan = new javax.swing.JPanel();
        lPelanggan = new javax.swing.JLabel();
        pTransaksi = new javax.swing.JPanel();
        lTransaksi = new javax.swing.JLabel();
        pLaporan = new javax.swing.JPanel();
        lLaporan = new javax.swing.JLabel();
        pBeranda = new javax.swing.JPanel();
        lBeranda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        deskPane = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moza Laundry");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(177, 81, 57));

        jPanel3.setBackground(new java.awt.Color(177, 81, 57));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(77, 200, 120));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Moza");

        jLabel2.setBackground(new java.awt.Color(77, 200, 120));
        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laundry");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pJenisLayanan.setBackground(new java.awt.Color(177, 81, 57));
        pJenisLayanan.setName("pJenisLayanan"); // NOI18N
        pJenisLayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pJenisLayananMouseClicked(evt);
            }
        });

        lJenis.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lJenis.setForeground(new java.awt.Color(242, 237, 215));
        lJenis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/service.png"))); // NOI18N
        lJenis.setText("Jenis Layanan");
        lJenis.setIconTextGap(10);

        javax.swing.GroupLayout pJenisLayananLayout = new javax.swing.GroupLayout(pJenisLayanan);
        pJenisLayanan.setLayout(pJenisLayananLayout);
        pJenisLayananLayout.setHorizontalGroup(
            pJenisLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJenisLayananLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lJenis)
                .addGap(12, 12, 12))
        );
        pJenisLayananLayout.setVerticalGroup(
            pJenisLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJenisLayananLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lJenis)
                .addGap(20, 20, 20))
        );

        pPelanggan.setBackground(new java.awt.Color(177, 81, 57));
        pPelanggan.setName("pPelanggan"); // NOI18N
        pPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPelangganMouseClicked(evt);
            }
        });

        lPelanggan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lPelanggan.setForeground(new java.awt.Color(242, 237, 215));
        lPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N
        lPelanggan.setText("Pelanggan");
        lPelanggan.setIconTextGap(10);

        javax.swing.GroupLayout pPelangganLayout = new javax.swing.GroupLayout(pPelanggan);
        pPelanggan.setLayout(pPelangganLayout);
        pPelangganLayout.setHorizontalGroup(
            pPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPelangganLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lPelanggan)
                .addGap(12, 12, 12))
        );
        pPelangganLayout.setVerticalGroup(
            pPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPelangganLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lPelanggan)
                .addGap(20, 20, 20))
        );

        pTransaksi.setBackground(new java.awt.Color(177, 81, 57));
        pTransaksi.setName("pTransaksi"); // NOI18N
        pTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTransaksiMouseClicked(evt);
            }
        });

        lTransaksi.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lTransaksi.setForeground(new java.awt.Color(242, 237, 215));
        lTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/payment.png"))); // NOI18N
        lTransaksi.setText("Transaksi");
        lTransaksi.setIconTextGap(10);

        javax.swing.GroupLayout pTransaksiLayout = new javax.swing.GroupLayout(pTransaksi);
        pTransaksi.setLayout(pTransaksiLayout);
        pTransaksiLayout.setHorizontalGroup(
            pTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTransaksiLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lTransaksi)
                .addGap(12, 12, 12))
        );
        pTransaksiLayout.setVerticalGroup(
            pTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTransaksiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTransaksi)
                .addGap(20, 20, 20))
        );

        pLaporan.setBackground(new java.awt.Color(177, 81, 57));
        pLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLaporanMouseClicked(evt);
            }
        });

        lLaporan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lLaporan.setForeground(new java.awt.Color(242, 237, 215));
        lLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laporan.png"))); // NOI18N
        lLaporan.setText("Laporan");
        lLaporan.setIconTextGap(10);

        javax.swing.GroupLayout pLaporanLayout = new javax.swing.GroupLayout(pLaporan);
        pLaporan.setLayout(pLaporanLayout);
        pLaporanLayout.setHorizontalGroup(
            pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLaporanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lLaporan)
                .addGap(12, 12, 12))
        );
        pLaporanLayout.setVerticalGroup(
            pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLaporanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lLaporan)
                .addGap(20, 20, 20))
        );

        pBeranda.setBackground(new java.awt.Color(177, 81, 57));
        pBeranda.setName("pBeranda"); // NOI18N
        pBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pBerandaMouseClicked(evt);
            }
        });

        lBeranda.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lBeranda.setForeground(new java.awt.Color(242, 237, 215));
        lBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beranda.png"))); // NOI18N
        lBeranda.setText("Beranda");
        lBeranda.setIconTextGap(10);
        lBeranda.setName("btnBeranda"); // NOI18N

        javax.swing.GroupLayout pBerandaLayout = new javax.swing.GroupLayout(pBeranda);
        pBeranda.setLayout(pBerandaLayout);
        pBerandaLayout.setHorizontalGroup(
            pBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBerandaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lBeranda)
                .addGap(12, 12, 12))
        );
        pBerandaLayout.setVerticalGroup(
            pBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBerandaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lBeranda)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pJenisLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pJenisLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 650));

        jPanel2.setBackground(new java.awt.Color(177, 81, 57));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        deskPane.setBackground(new java.awt.Color(242, 237, 215));
        deskPane.setMaximumSize(new java.awt.Dimension(710, 600));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 10.png"))); // NOI18N

        deskPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPaneLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel4)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPaneLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel4)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        getContentPane().add(deskPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 710, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pJenisLayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pJenisLayananMouseClicked
        // TODO add your handling code here:
        pJenisLayanan.setBackground(new Color(92,56,32));
        pPelanggan.setBackground(new Color(177, 81, 57));
        pTransaksi.setBackground(new Color(177, 81, 57));
        pLaporan.setBackground(new Color(177, 81, 57));
        pBeranda.setBackground(new Color(177, 81, 57));
        
        
        
        JenisLayanan JL = new JenisLayanan();
        deskPane.add(JL);
        JL.setVisible(true);
    }//GEN-LAST:event_pJenisLayananMouseClicked

    private void pPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPelangganMouseClicked
        // TODO add your handling code here:
        pJenisLayanan.setBackground(new Color(177, 81, 57));
        pPelanggan.setBackground(new Color(92, 56, 32));
        pTransaksi.setBackground(new Color(177, 81, 57));
        pLaporan.setBackground(new Color(177, 81, 57));
        pBeranda.setBackground(new Color(177, 81, 57));
        
        Pelanggan P = new Pelanggan();
        deskPane.add(P);
        P.setVisible(true);
    }//GEN-LAST:event_pPelangganMouseClicked

    private void pTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTransaksiMouseClicked
        // TODO add your handling code here:
        pJenisLayanan.setBackground(new Color(177, 81, 57));
        pPelanggan.setBackground(new Color(177, 81, 57));
        pTransaksi.setBackground(new Color(92, 56, 32));
        pLaporan.setBackground(new Color(177, 81, 57));
        pBeranda.setBackground(new Color(177, 81, 57));
        Transaksi T = new Transaksi();
        deskPane.add(T);
        T.setVisible(true);
    }//GEN-LAST:event_pTransaksiMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        Display D = new Display();
        deskPane.add(D);
        D.setVisible(true);
        
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void pLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLaporanMouseClicked
        // TODO add your handling code here:
        pJenisLayanan.setBackground(new Color(177, 81, 57));
        pPelanggan.setBackground(new Color(177, 81, 57));
        pTransaksi.setBackground(new Color(177, 81, 57));
        pLaporan.setBackground(new Color(92, 56, 32));
        pBeranda.setBackground(new Color(177, 81, 57));
        Laporan L = new Laporan();
        deskPane.add(L);
        L.setVisible(true);
    }//GEN-LAST:event_pLaporanMouseClicked

    private void pBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBerandaMouseClicked
        // TODO add your handling code here:
        pJenisLayanan.setBackground(new Color(177, 81, 57));
        pPelanggan.setBackground(new Color(177, 81, 57));
        pBeranda.setBackground(new Color(92, 56, 32));
        pLaporan.setBackground(new Color(177, 81, 57));
        pTransaksi.setBackground(new Color(177, 81, 57));
        Beranda B = new Beranda();
        deskPane.add(B);
        B.setVisible(true);
    }//GEN-LAST:event_pBerandaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lBeranda;
    private javax.swing.JLabel lJenis;
    private javax.swing.JLabel lLaporan;
    private javax.swing.JLabel lPelanggan;
    private javax.swing.JLabel lTransaksi;
    private javax.swing.JPanel pBeranda;
    private javax.swing.JPanel pJenisLayanan;
    private javax.swing.JPanel pLaporan;
    private javax.swing.JPanel pPelanggan;
    private javax.swing.JPanel pTransaksi;
    // End of variables declaration//GEN-END:variables
}


